name: "Auto test PR"
on:
  issue_comment:
    types: [created]
jobs:
  autoTestPR:
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, 'auto exclude test')
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: check python version
        run: |
          python -V
      - name: install xml module
        run: |
          pip install lxml
      - name: checkout current repo
        uses: actions/checkout@v3
        with:
          path: 'tests'
      - name: checkout TKG repo
        uses: actions/checkout@v3
        with:
          repository: 'adoptium/TKG.git'
          ref: 'master'
          path: 'TKG'
      - name: run script
        env:
          comment_body: ${{ github.event.comment.body }}
        run: |
          git config --list
          python TKG/scripts/testBot/disable.py -m "$comment_body" -c "${{ github.event.comment.html_url }}" -d "$GITHUB_WORKSPACE/tests"
      - name: test cannot be found
        if: failure()
        run: |
          curl -u github-actions:${{ secrets.GITHUB_TOKEN }} -d '{ "body":  "The specified test cannot be excluded. Action run: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}" }' -X POST ${{ github.event.issue.comments_url }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5b4a9f6a9e2af26e5f02351490b90d01eb8ec1e5 # v5.0.0
        with:
          path: 'tests'
          title: '${{ github.event.comment.body }}'
          body: |
            related: ${{ github.event.comment.html_url }}
            triggered by @${{ github.event.comment.user.login }}
          commit-message: |
            AUTO: ${{ github.event.comment.body }}
            - related: ${{ github.event.comment.html_url }}
          branch: 'autoTestPR'
          branch-suffix: 'random'
          signoff: 'true'
      - name: add label
        run: |
          curl -u github-actions:${{ secrets.GITHUB_TOKEN }} -d '{"labels":["test excluded"]}' -X POST ${{ github.event.issue.url }}/labels
